#include "packet_encode.h"
#include "protocol.h"
#include <time.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************
// DISCLAIMER: THIS FILE WAS AUTO-GENERATED BY template_generator.py
// DO NOT MODIFY THIS FILE DIRECTLY!
// TO MODIFY THE PROTOCOL, EDIT protocol.json AND RE-RUN template_generator.py
//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************

int is_command_packet(uint8_t* packet, size_t packet_size) {
	if (packet_size != 7) return -1; // Incorrect size
	if (packet[1] != COMMAND_MSG_ID) return -1; // Incorrect command id
	return packet[3];
}

int get_command_uuid(uint8_t* packet) {
	return packet[4];
}

int generate_ack_packet(uint8_t *packet, size_t packet_size, uint8_t *generated_packet) {
  if (packet_size != 7) {
    return -1;
  }
  if (!verify_packet(packet, packet_size)) {
    return -2;
  }

  int command_id = is_command_packet(packet, packet_size);
  if (command_id < 0 || command_id > 255) {
    return -3;
  }
  uint8_t payload[2];
  payload[0] = command_id; // command id
  payload[1] = get_command_uuid(packet); // command uuid
  int written = generate_packet(payload, 2, generated_packet, COMMAND_ACK_MSG_ID);
  if (written != 7) {
    return -4;
  }
  return 7;
}

size_t generate_command_payload(uint8_t *buffer, uint8_t command_id, uint8_t command_counter) {
	memcpy(buffer, &command_id, sizeof(command_id));	// Byte 1: command id
	memcpy(buffer + sizeof(command_id), &command_counter, sizeof(command_counter)); // byte 2 command counter
	return sizeof(command_id) + sizeof(command_counter);
}

bool extract_command(uint8_t *buffer, uint8_t buffer_size, struct CommandStruct* destination) {
	if (buffer_size != 2) return false;
	destination->command_id = buffer[0];
	destination->command_counter = buffer[1];
	return true;
}

int get_msg_size(int message_id) {
	switch (message_id) {
    	case ROCKETSTATE_MSG_ID:
			return ROCKETSTATE_SIZE;
    	case SERVODEFLECTIONS_MSG_ID:
			return SERVODEFLECTIONS_SIZE;
    	default:
			return -1;
	}
}

bool is_data_send_msg(int message_id) {
	return (message_id >= 10) && (message_id <= 10 + 2);
}

#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	
    bool convert_data_msg_to_sql_cmd(int message_id, uint8_t *data, size_t data_size, char *sql_cmd) {
		if (!is_data_send_msg(message_id)) {
			return false;
		}

		switch (message_id) {
    	    case ROCKETSTATE_MSG_ID: {
        if (data_size != ROCKETSTATE_SIZE) {
          printf("warning: wrong data size!\n");
        }
				struct RocketState cvt_data;
				RocketState_decode(data, &cvt_data);
				ROCKETSTATE_SQL_ADD_ENTRY(sql_cmd, &cvt_data);
				return true;
			} 
    	    case SERVODEFLECTIONS_MSG_ID: {
        if (data_size != SERVODEFLECTIONS_SIZE) {
          printf("warning: wrong data size!\n");
        }
				struct ServoDeflections cvt_data;
				ServoDeflections_decode(data, &cvt_data);
				SERVODEFLECTIONS_SQL_ADD_ENTRY(sql_cmd, &cvt_data);
				return true;
			} 
    		default:
				return false;
		}
	}

#endif


void RocketState_encode(struct RocketState *input, uint8_t *output) {
		memcpy(output + 0, &input->rocket_state, 1);
		memcpy(output + 1, &input->timestamp, 8);

}

void RocketState_decode(uint8_t *input, struct RocketState *output) {
		memcpy(&output->rocket_state, input + 0, 1);
		memcpy(&output->timestamp, input + 1, 8);

}


void ServoDeflections_encode(struct ServoDeflections *input, uint8_t *output) {
		memcpy(output + 0, &input->servo_1_desired, 2);
		memcpy(output + 2, &input->servo_1_actual, 2);
		memcpy(output + 4, &input->servo_2_desired, 2);
		memcpy(output + 6, &input->servo_2_actual, 2);
		memcpy(output + 8, &input->servo_3_desired, 2);
		memcpy(output + 10, &input->servo_3_actual, 2);
		memcpy(output + 12, &input->servo_4_desired, 2);
		memcpy(output + 14, &input->servo_4_actual, 2);
		memcpy(output + 16, &input->timestamp, 8);

}

void ServoDeflections_decode(uint8_t *input, struct ServoDeflections *output) {
		memcpy(&output->servo_1_desired, input + 0, 2);
		memcpy(&output->servo_1_actual, input + 2, 2);
		memcpy(&output->servo_2_desired, input + 4, 2);
		memcpy(&output->servo_2_actual, input + 6, 2);
		memcpy(&output->servo_3_desired, input + 8, 2);
		memcpy(&output->servo_3_actual, input + 10, 2);
		memcpy(&output->servo_4_desired, input + 12, 2);
		memcpy(&output->servo_4_actual, input + 14, 2);
		memcpy(&output->timestamp, input + 16, 8);

}