#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <time.h>
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

// Uncomment this line to include SQL macros
//#define INCLUDE_PROTOCOL_SQL_MACROS

//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************
// DISCLAIMER: THIS FILE WAS AUTO-GENERATED BY template_generator.py
// DO NOT MODIFY THIS FILE DIRECTLY!
// TO MODIFY THE PROTOCOL, EDIT protocol.json AND RE-RUN template_generator.py
//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************

#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define WEB_SERVER_URL "http://0.0.0.0:8080"

	#define SET_ALL_NULL(x, len) for (int i = 0; i < (len); i++) x[i] = NULL
	#define FREE_ALL(x, len) for (int i = 0; i < (len); i++) free(x[i])

	#define COMMAND_API_PATH "/api/command/send"
#endif

/*
 * 0x00 command_id
 * 0x01 command_counter
 */
struct CommandStruct {
	uint8_t command_id;
	uint8_t command_counter;
};

#define COMMAND_MSG_ID 1
#define COMMAND_ACK_MSG_ID 2

/**
 * Checks if the inputted packet represents a command
 * 
 * @param packet the complete packet (payload + overhead)
 * @param packet_size the size of packet (should be 7, will return -1 otherwise)
 * @return		the command id, or -1 if the packet is not a command packet
 */
int is_command_packet(uint8_t* packet, size_t packet_size);

/**
 * Extracts the command uuid from a packet representing a command
 *
 * @param packet the complete packet (payload + overhead)
 * @return the command uuid
 */
int get_command_uuid(uint8_t* packet);

/**
 * Checks whether the given packet is a command packet, verifies it, and generates a return acknowledge packet.
 *
 * @param packet           original command packet
 * @param packet_size      original command packet's packet size (must be seven)
 * @param generated_packet ptr to store generated packet in. must be able to hold 7 bytes
 * @return                 positive generated packet size if success, failure if zero or negative
 */
int generate_ack_packet(uint8_t *packet, size_t packet_size, uint8_t *generated_packet);

/**
 * Generates a command payload given a command id and a command counter (should be passed into generate packet as raw data)
 * 
 * @param buffer the buffer where the generated command should be stored (at least 2 bytes)
 * @param command_id the desired command id
 * @param command_counter the desired command counter value
 * 
 * @return the size of the generated command (2 bytes)
 */
size_t generate_command_payload(uint8_t *buffer, uint8_t command_id, uint8_t command_counter);

/** Takes the payload from a command message and copies it into the given command struct
 * 
 * @param buffer the buffer where the command message payload is stored
 * @param buffer_size the size of the buffer (should be 2 bytes)
 * @param destination a pointer to the CommandStruct where the values whould be copied
 * @return true if the operation was successful, and false otherwise
 */
bool extract_command(uint8_t *buffer, uint8_t buffer_size, struct CommandStruct* destination);

/**
 * Calculates the size of a message given its ID
 * @param id	the ID of the message
 * @return		the size of the message in bytes, or -1 if the message id is invalid
 */
int get_msg_size(int message_id);

/**
 * Returns true if this message id corresponds to a data packet, and false otherwise
 */
bool is_data_send_msg(int message_id);

#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define MAX_SQL_WRITE_CMD_SIZE 192

	#define ALL_SQL_TABLE_CREATE_COMMANDS ROCKETSTATE_SQL_TABLE_GEN, SERVODEFLECTIONS_SQL_TABLE_GEN

	#define NUM_SQL_TABLES 2

	/**
	 * Takes a recieved data packet and converts it into an SQL command
	 * 
	 * @param message_id	The id associated with this message
	 * @param data			  The data recieved (as an array of bytes)
   * @param data_size   Length of the data received
	 * @param sql_cmd		  A char* buffer where the SQL command will be saved (must be at least as big as MAX_SQL_WRITE_CMD_SIZE)
	 * 
	 * @return				true if the operation was successful, and false otherwise.
	 */
	bool convert_data_msg_to_sql_cmd(int message_id, uint8_t *data, size_t data_size, char *sql_cmd);

	#define HANDLE_API_INPUT(db, hm) \
		if (mg_match(hm->uri, mg_str(ROCKETSTATE_API_PATH), NULL)) { \
			char *data[ROCKETSTATE_NUM_VALUES]; \
			SET_ALL_NULL(data, ROCKETSTATE_NUM_VALUES); \
			query_sql_with_callback(db, data, ROCKETSTATE_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", ROCKETSTATE_SQL_SELECT_TO_JSON(data)); \
			FREE_ALL(data, ROCKETSTATE_NUM_VALUES); \
		} else if (mg_match(hm->uri, mg_str(SERVODEFLECTIONS_API_PATH), NULL)) { \
			char *data[SERVODEFLECTIONS_NUM_VALUES]; \
			SET_ALL_NULL(data, SERVODEFLECTIONS_NUM_VALUES); \
			query_sql_with_callback(db, data, SERVODEFLECTIONS_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", SERVODEFLECTIONS_SQL_SELECT_TO_JSON(data)); \
			FREE_ALL(data, SERVODEFLECTIONS_NUM_VALUES); \
		}

#endif

#endif