#include "packet_encode.h"
#include "protocol.h"
#include <time.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************
// DISCLAIMER: THIS FILE WAS AUTO-GENERATED BY template_generator.py
// DO NOT MODIFY THIS FILE DIRECTLY!
// TO MODIFY THE PROTOCOL, EDIT protocol.json AND RE-RUN template_generator.py
//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************

int is_command_packet(uint8_t* packet, size_t packet_size) {
	if (packet_size != 7) return -1; // Incorrect size
	if (packet[1] != COMMAND_MSG_ID) return -1; // Incorrect command id
	return packet[3];
}

int get_command_uuid(uint8_t* packet) {
	return packet[4];
}

int generate_ack_packet(uint8_t *packet, size_t packet_size, uint8_t *generated_packet) {
  if (packet_size != 7) {
    return -1;
  }
  if (!verify_packet(packet, packet_size)) {
    return -2;
  }

  int command_id = is_command_packet(packet, packet_size);
  if (command_id < 0 || command_id > 255) {
    return -3;
  }
  uint8_t payload[2];
  payload[0] = command_id; // command id
  payload[1] = get_command_uuid(packet); // command uuid
  int written = generate_packet(payload, 2, generated_packet, COMMAND_ACK_MSG_ID);
  if (written != 7) {
    return -4;
  }
  return 7;
}

size_t generate_command_payload(uint8_t *buffer, uint8_t command_id, uint8_t command_counter) {
	memcpy(buffer, &command_id, sizeof(command_id));	// Byte 1: command id
	memcpy(buffer + sizeof(command_id), &command_counter, sizeof(command_counter)); // byte 2 command counter
	return sizeof(command_id) + sizeof(command_counter);
}

bool extract_command(uint8_t *buffer, uint8_t buffer_size, struct CommandStruct* destination) {
	if (buffer_size != 2) return false;
	destination->command_id = buffer[0];
	destination->command_counter = buffer[1];
	return true;
}

bool is_data_send_msg(int message_id) {
	return (message_id >= 10) && (message_id <= 10 + 2);
}