#ifndef STATE_FLASH_H
#define STATE_FLASH_H

#define BEGIN_STATE_FLASH_NOTIFICATION_BIT 0x01
#define FS_READY_NOTIFICATION_BIT 0x01
#define FLASHCHIP_READY_NOTIFICAITON_BIT 0x02
#define FLASH_STATE_NOTIFICATION_BIT 0x01
#define FLASH_FS_NOTIFICATION_BIT 0x02

void state_flash_task(void *args);

#endif
