#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <time.h>
#include <stdbool.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

// Uncomment this line to include SQL macros
//#define INCLUDE_PROTOCOL_SQL_MACROS

//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************
// DISCLAIMER: THIS FILE WAS AUTO-GENERATED BY template_generator.py
// DO NOT MODIFY THIS FILE DIRECTLY!
// TO MODIFY THE PROTOCOL, EDIT protocol.json AND RE-RUN template_generator.py
//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************

#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define WEB_SERVER_URL "http://0.0.0.0:8080"

	#define SET_ALL_NULL(x, len) for (int i = 0; i < (len); i++) x[i] = NULL
	#define FREE_ALL(x, len) for (int i = 0; i < (len); i++) free(x[i])

	#define COMMAND_API_PATH "/api/command/send"
#endif

/*
 * 0x00 command_id
 * 0x01 command_counter
 */
struct CommandStruct {
	uint8_t command_id;
	uint8_t command_counter;
};

#define COMMAND_MSG_ID 1
#define COMMAND_ACK_MSG_ID 2

#define IGNITE_COMMAND_ID 1
#define ZERO_SERVOS_COMMAND_ID 2
#define PING_ROCKET_COMMAND_ID 3

#define NUM_COMMAND_TYPES 3

/**
 * Checks if the inputted packet represents a command
 * 
 * @param packet the complete packet (payload + overhead)
 * @param packet_size the size of packet (should be 7, will return -1 otherwise)
 * @return		the command id, or -1 if the packet is not a command packet
 */
int is_command_packet(uint8_t* packet, size_t packet_size);

/**
 * Extracts the command uuid from a packet representing a command
 *
 * @param packet the complete packet (payload + overhead)
 * @return the command uuid
 */
int get_command_uuid(uint8_t* packet);

/**
 * Checks whether the given packet is a command packet, verifies it, and generates a return acknowledge packet.
 *
 * @param packet           original command packet
 * @param packet_size      original command packet's packet size (must be seven)
 * @param generated_packet ptr to store generated packet in. must be able to hold 7 bytes
 * @return                 positive generated packet size if success, failure if zero or negative
 */
int generate_ack_packet(uint8_t *packet, size_t packet_size, uint8_t *generated_packet);

/**
 * Generates a command payload given a command id and a command counter (should be passed into generate packet as raw data)
 * 
 * @param buffer the buffer where the generated command should be stored (at least 2 bytes)
 * @param command_id the desired command id
 * @param command_counter the desired command counter value
 * 
 * @return the size of the generated command (2 bytes)
 */
size_t generate_command_payload(uint8_t *buffer, uint8_t command_id, uint8_t command_counter);

/** Takes the payload from a command message and copies it into the given command struct
 * 
 * @param buffer the buffer where the command message payload is stored
 * @param buffer_size the size of the buffer (should be 2 bytes)
 * @param destination a pointer to the CommandStruct where the values whould be copied
 * @return true if the operation was successful, and false otherwise
 */
bool extract_command(uint8_t *buffer, uint8_t buffer_size, struct CommandStruct* destination);

/**
 * Returns true if this message id corresponds to a data packet, and false otherwise
 */
bool is_data_send_msg(int message_id);


#endif