#ifndef NUCLEO_F429ZI_HALAL_H
#define NUCLEO_F429ZI_HALAL_H

#include "halal.h"


#define HALAL_RCC_MODULE_ENABLED
#define HALAL_RCC_NUCLEO_F429ZI_ENABLED

#define HALAL_TIMEBASE_MODULE_ENABLED
#define HALAL_TIMEBASE_TIM_ENABLED
#define HALAL_TIMEBASE_TIM_INSTANCE                 TIM1
#define HALAL_TIMEBASE_TIM_RCC_EN()                 __HAL_RCC_TIM1_CLK_ENABLE()
#define HALAL_TIMEBASE_TIM_IRQn                     TIM1_UP_TIM10_IRQn
#define HALAL_TIMEBASE_TIM_ISR                      TIM1_UP_TIM10_IRQHandler

#define HALAL_DEBUG_MODULE_ENABLED
#define HALAL_DEBUG_UART_ENABLED
#define HALAL_DEBUG_UART_INSTANCE                   USART3
#define HALAL_DEBUG_UART_BAUDRATE                   115200
#define HALAL_DEBUG_UART_WORDLENGTH                 UART_WORDLENGTH_8B
#define HALAL_DEBUG_UART_STOPBITS                   UART_STOPBITS_1
#define HALAL_DEBUG_UART_PARITY                     UART_PARITY_NONE
#define HALAL_DEBUG_UART_RCC_EN()                   __HAL_RCC_USART3_CLK_ENABLE()
#define HALAL_DEBUG_UART_TX_PIN                     GPIO_PIN_8
#define HALAL_DEBUG_UART_TX_PORT                    GPIOD
#define HALAL_DEBUG_UART_RX_PIN                     GPIO_PIN_9
#define HALAL_DEBUG_UART_RX_PORT                    GPIOD
#define HALAL_DEBUG_UART_AF                         GPIO_AF7_USART3

#define HALAL_RADIO_MODULE_ENABLED
#define HALAL_RADIO_UART_ENABLED
#define HALAL_RADIO_UART_INSTANCE                   USART2
#define HALAL_RADIO_UART_BAUDRATE                   57600
#define HALAL_RADIO_UART_WORDLENGTH                 UART_WORDLENGTH_8B
#define HALAL_RADIO_UART_STOPBITS                   UART_STOPBITS_1
#define HALAL_RADIO_UART_PARITY                     UART_PARITY_NONE
#define HALAL_RADIO_UART_RCC_EN()                   __HAL_RCC_USART2_CLK_ENABLE()
#define HALAL_RADIO_UART_TX_PIN                     GPIO_PIN_5
#define HALAL_RADIO_UART_TX_PORT                    GPIOD
#define HALAL_RADIO_UART_RX_PIN                     GPIO_PIN_6
#define HALAL_RADIO_UART_RX_PORT                    GPIOD
#define HALAL_RADIO_UART_AF                         GPIO_AF7_USART2
#define HALAL_RADIO_UART_IRQn                       USART2_IRQn
#define HALAL_RADIO_UART_ISR                        USART2_IRQHandler

#define HALAL_STATE_ESTIMATION_MODULE_ENABLED
#define HALAL_STATE_ESTIMATION_UART_ENABLED
#define HALAL_STATE_ESTIMATION_UART_INSTANCE        USART6
#define HALAL_STATE_ESTIMATION_UART_BAUDRATE        115200
#define HALAL_STATE_ESTIMATION_UART_WORDLENGTH      UART_WORDLENGTH_8B
#define HALAL_STATE_ESTIMATION_UART_STOPBITS        UART_STOPBITS_1
#define HALAL_STATE_ESTIMATION_UART_PARITY          UART_PARITY_NONE
#define HALAL_STATE_ESTIMATION_UART_RCC_EN()        __HAL_RCC_USART6_CLK_ENABLE()
#define HALAL_STATE_ESTIMATION_UART_TX_PIN          GPIO_PIN_6
#define HALAL_STATE_ESTIMATION_UART_TX_PORT         GPIOC
#define HALAL_STATE_ESTIMATION_UART_RX_PIN          GPIO_PIN_9
#define HALAL_STATE_ESTIMATION_UART_RX_PORT         GPIOG
#define HALAL_STATE_ESTIMATION_UART_AF              GPIO_AF8_USART6
#define HALAL_STATE_ESTIMATION_UART_IRQn            USART6_IRQn
#define HALAL_STATE_ESTIMATION_UART_ISR             USART6_IRQHandler
#define HALAL_STATE_ESTIMATION_PACKET_SIZE          118

#define HALAL_STORAGE_MODULE_ENABLED
#define HALAL_STORAGE_USB_ENABLED
#define HALAL_STORAGE_USB_VBUS_PIN                  GPIO_PIN_9
#define HALAL_STORAGE_USB_VBUS_PORT                 GPIOA
#define HALAL_STORAGE_USB_VBUS_EN_PIN               GPIO_PIN_6
#define HALAL_STORAGE_USB_VBUS_EN_PORT              GPIOG
#define HALAL_STORAGE_USB_VBUS_EN_STATE             GPIO_PIN_SET
#define HALAL_STORAGE_USB_DM_PIN                    GPIO_PIN_11
#define HALAL_STORAGE_USB_DM_PORT                   GPIOA
#define HALAL_STORAGE_USB_DP_PIN                    GPIO_PIN_12
#define HALAL_STORAGE_USB_DP_PORT                   GPIOA
#define HALAL_STORAGE_USB_ID_PIN                    GPIO_PIN_10
#define HALAL_STORAGE_USB_ID_PORT                   GPIOA
#define HALAL_STORAGE_USB_CLK_ENABLE()              __HAL_RCC_USB_OTG_FS_CLK_ENABLE()
#define HALAL_STORAGE_USB_AF                        GPIO_AF10_OTG_FS
#define HALAL_STORAGE_USB_IRQn                      OTG_FS_IRQn
#define HALAL_STORAGE_USB_ISR                       OTG_FS_IRQHandler
#define HALAL_STORAGE_USB_INSTANCE                  USB_OTG_FS
#define HALAL_STORAGE_USB_SPEED                     HCD_SPEED_FULL

#define HALAL_FLASH_CHIP_MODULE_ENABLED
#define HALAL_FAKE_FLASH_CHIP_ENABLED
#define HALAL_FAKE_FLASH_CHIP_PAGE_SIZE            256
#define HALAL_FAKE_FLASH_CHIP_N_PAGES              32

#define HALAL_ADC_MODULE_ENABLED
#define HALAL_ADC_INTERNAL_ADC1_CLK_EN()           __HAL_RCC_ADC1_CLK_ENABLE()
#define HALAL_ADC_INTERNAL_ADC2_CLK_EN()           __HAL_RCC_ADC2_CLK_ENABLE()
#define HALAL_ADC_INTERNAL_ADC3_CLK_EN()           __HAL_RCC_ADC3_CLK_ENABLE()

#define HALAL_ADC_JET_VANES_ENABLED

#define HALAL_ADC_JET_VANES_USE_ADC1
#define HALAL_ADC1_HAL_DMA_ISR                      DMA2_Stream0_IRQHandler
#define HALAL_ADC_JET_VANES_ADC1_CLOCK_PRESCALER    ADC_CLOCK_SYNC_PCLK_DIV4
#define HALAL_ADC_JET_VANES_ADC1_RESOLUTION         ADC_RESOLUTION_12B
#define HALAL_ADC_JET_VANES_ADC1_DMA_STREAM         DMA2_Stream0
#define HALAL_ADC_JET_VANES_ADC1_DMA_CHANNEL        DMA_CHANNEL_0
#define HALAL_ADC_JET_VANES_ADC1_DMA_IRQ            DMA2_Stream0_IRQn

#define HALAL_ADC_JET_VANES_USE_ADC2
#define HALAL_ADC2_HAL_DMA_ISR                      DMA2_Stream2_IRQHandler
#define HALAL_ADC_JET_VANES_ADC2_CLOCK_PRESCALER    ADC_CLOCK_SYNC_PCLK_DIV4
#define HALAL_ADC_JET_VANES_ADC2_RESOLUTION         ADC_RESOLUTION_12B
#define HALAL_ADC_JET_VANES_ADC2_DMA_STREAM         DMA2_Stream2
#define HALAL_ADC_JET_VANES_ADC2_DMA_CHANNEL        DMA_CHANNEL_1
#define HALAL_ADC_JET_VANES_ADC2_DMA_IRQ            DMA2_Stream2_IRQn

#define HALAL_ADC_JET_VANES_USE_ADC3
#define HALAL_ADC3_HAL_DMA_ISR                      DMA2_Stream1_IRQHandler
#define HALAL_ADC_JET_VANES_ADC3_CLOCK_PRESCALER    ADC_CLOCK_SYNC_PCLK_DIV4
#define HALAL_ADC_JET_VANES_ADC3_RESOLUTION         ADC_RESOLUTION_12B
#define HALAL_ADC_JET_VANES_ADC3_DMA_STREAM         DMA2_Stream1
#define HALAL_ADC_JET_VANES_ADC3_DMA_CHANNEL        DMA_CHANNEL_2
#define HALAL_ADC_JET_VANES_ADC3_DMA_IRQ            DMA2_Stream1_IRQn

/*ADC3_IN9 = PF3*/
#define HALAL_ADC_JET_VANES_PYRO_I_0_MODULE         HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_PYRO_I_0_CHANNEL        ADC_CHANNEL_9
#define HALAL_ADC_JET_VANES_PYRO_I_0_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_PYRO_I_0_GPIO_PIN       GPIO_PIN_3
#define HALAL_ADC_JET_VANES_PYRO_I_0_GPIO_PORT      GPIOF

/*ADC3_IN14 = PF4*/
#define HALAL_ADC_JET_VANES_PYRO_I_1_MODULE         HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_PYRO_I_1_CHANNEL        ADC_CHANNEL_14
#define HALAL_ADC_JET_VANES_PYRO_I_1_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_PYRO_I_1_GPIO_PIN       GPIO_PIN_4
#define HALAL_ADC_JET_VANES_PYRO_I_1_GPIO_PORT      GPIOF

/*ADC3_IN4 = PF6*/
#define HALAL_ADC_JET_VANES_PYRO_I_2_MODULE         HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_PYRO_I_2_CHANNEL        ADC_CHANNEL_4
#define HALAL_ADC_JET_VANES_PYRO_I_2_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_PYRO_I_2_GPIO_PIN       GPIO_PIN_6
#define HALAL_ADC_JET_VANES_PYRO_I_2_GPIO_PORT      GPIOF

/*ADC3_IN5 = PF7*/
#define HALAL_ADC_JET_VANES_VCC_I_MODULE            HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_VCC_I_CHANNEL           ADC_CHANNEL_5
#define HALAL_ADC_JET_VANES_VCC_I_SAMPLE_TIME       ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_VCC_I_GPIO_PIN          GPIO_PIN_7
#define HALAL_ADC_JET_VANES_VCC_I_GPIO_PORT         GPIOF

/*ADC3_IN6 = PF8*/
#define HALAL_ADC_JET_VANES_SERVO_0_MODULE         HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_SERVO_0_CHANNEL        ADC_CHANNEL_6
#define HALAL_ADC_JET_VANES_SERVO_0_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_SERVO_0_GPIO_PIN       GPIO_PIN_8
#define HALAL_ADC_JET_VANES_SERVO_0_GPIO_PORT      GPIOF

/*ADC3_IN7 = PF9*/
#define HALAL_ADC_JET_VANES_SERVO_1_MODULE         HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_SERVO_1_CHANNEL        ADC_CHANNEL_7
#define HALAL_ADC_JET_VANES_SERVO_1_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_SERVO_1_GPIO_PIN       GPIO_PIN_9
#define HALAL_ADC_JET_VANES_SERVO_1_GPIO_PORT      GPIOF

/*ADC3_IN8 = PF10*/
#define HALAL_ADC_JET_VANES_SERVO_2_MODULE         HALAL_ADC_INTERNAL_3
#define HALAL_ADC_JET_VANES_SERVO_2_CHANNEL        ADC_CHANNEL_8
#define HALAL_ADC_JET_VANES_SERVO_2_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_SERVO_2_GPIO_PIN       GPIO_PIN_10
#define HALAL_ADC_JET_VANES_SERVO_2_GPIO_PORT      GPIOF

/*ADC1_IN10 = PC0 */
#define HALAL_ADC_JET_VANES_SERVO_3_MODULE         HALAL_ADC_INTERNAL_1
#define HALAL_ADC_JET_VANES_SERVO_3_CHANNEL        ADC_CHANNEL_10
#define HALAL_ADC_JET_VANES_SERVO_3_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_SERVO_3_GPIO_PIN       GPIO_PIN_0
#define HALAL_ADC_JET_VANES_SERVO_3_GPIO_PORT      GPIOC

/* ADC2_IN11 = PC1*/
#define HALAL_ADC_JET_VANES_SERVO_4_MODULE         HALAL_ADC_INTERNAL_2
#define HALAL_ADC_JET_VANES_SERVO_4_CHANNEL        ADC_CHANNEL_11
#define HALAL_ADC_JET_VANES_SERVO_4_SAMPLE_TIME    ADC_SAMPLETIME_28CYCLES
#define HALAL_ADC_JET_VANES_SERVO_4_GPIO_PIN       GPIO_PIN_1
#define HALAL_ADC_JET_VANES_SERVO_4_GPIO_PORT      GPIOC

/* Barometer */
#define HALAL_BAROMETER_MODULE_ENABLED
#define HALAL_BAROMETER_MS5607_ENABLED
#define HALAL_BAROMETER_MS5607_SPI_MODULE           SPI3
#define HALAL_BAROMETER_MS5607_SPI_AF               GPIO_AF5_SPI3
#define HALAL_BAROMETER_MS5607_SPI_CLK_EN()         __HAL_RCC_SPI3_CLK_ENABLE()
#define HALAL_BAROMETER_MS5607_SPI_CS_PORT          GPIOC
#define HALAL_BAROMETER_MS5607_SPI_CS_PIN           GPIO_PIN_6
#define HALAL_BAROMETER_MS5607_SPI_GPIO_PORT        GPIOC
#define HALAL_BAROMETER_MS5607_SPI_SCK_PIN          GPIO_PIN_10
#define HALAL_BAROMETER_MS5607_SPI_MISO_PIN         GPIO_PIN_11
#define HALAL_BAROMETER_MS5607_SPI_MOSI_PIN         GPIO_PIN_12

/* Magnetometer */
#define HALAL_MAGNETOMETER_MODULE_ENABLED
#define HALAL_MAGNETOMETER_LIS3MDL_ENABLED
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_TIMEOUT_MS       10
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_AF               GPIO_AF5_SPI4
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_CLK_EN()         __HAL_RCC_SPI4_CLK_ENABLE();
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_GPIO_PORT        GPIOE
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_SCK_PIN          GPIO_PIN_2
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_MISO_PIN         GPIO_PIN_5
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_MOSI_PIN         GPIO_PIN_6
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_CS_PIN           GPIO_PIN_5
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_CS_PORT          GPIOC
#define HALAL_MAGNETOMETER_LIS3MDL_SPI_MODULE           SPI4
#define HALAL_MAGNETOMETER_LIS3MDL_TEMP_ENABLE          LIS3MDL_TEMP_EN       
#define HALAL_MAGNETOMETER_LIS3MDL_DATA_RATE            LIS3MDL_ODR_40HZ
#define HALAL_MAGNETOMETER_LIS3MDL_SELF_TEST            LIS3MDL_SELF_TEST_DIS
#define HALAL_MAGNETOMETER_LIS3MDL_FULL_SCALE           LIS3MDL_FS_4Gauss
#define HALAL_MAGNETOMETER_LIS3MDL_Z_AXIS_MODE          LIS3MDL_Z_UHP
#define HALAL_MAGNETOMETER_LIS3MDL_ENDIANNESS           LIS3MDL_LITTLE_ENDIAN

#endif