#ifndef NUCLEO_F429ZI_HALAL_H
#define NUCLEO_F429ZI_HALAL_H

#define HALAL_DEBUG_MODULE_ENABLED
#define HALAL_DEBUG_UART_ENABLED
#define HALAL_DEBUG_UART_INSTANCE                   USART3
#define HALAL_DEBUG_UART_BAUDRATE                   115200
#define HALAL_DEBUG_UART_WORDLENGTH                 UART_WORDLENGTH_8B
#define HALAL_DEBUG_UART_STOPBITS                   UART_STOPBITS_1
#define HALAL_DEBUG_UART_PARITY                     UART_PARITY_NONE
#define HALAL_DEBUG_UART_RCC_EN()                   __HAL_RCC_USART3_CLK_ENABLE()
#define HALAL_DEBUG_UART_TX_PIN                     GPIO_PIN_8
#define HALAL_DEBUG_UART_TX_PORT                    GPIOD
#define HALAL_DEBUG_UART_RX_PIN                     GPIO_PIN_9
#define HALAL_DEBUG_UART_RX_PORT                    GPIOD
#define HALAL_DEBUG_UART_AF                         GPIO_AF7_USART3

#define HALAL_RADIO_MODULE_ENABLED
#define HALAL_RADIO_UART_ENABLED
#define HALAL_RADIO_UART_INSTANCE                   USART2
#define HALAL_RADIO_UART_BAUDRATE                   57600
#define HALAL_RADIO_UART_WORDLENGTH                 UART_WORDLENGTH_8B
#define HALAL_RADIO_UART_STOPBITS                   UART_STOPBITS_1
#define HALAL_RADIO_UART_PARITY                     UART_PARITY_NONE
#define HALAL_RADIO_UART_RCC_EN()                   __HAL_RCC_USART2_CLK_ENABLE()
#define HALAL_RADIO_UART_TX_PIN                     GPIO_PIN_5
#define HALAL_RADIO_UART_TX_PORT                    GPIOD
#define HALAL_RADIO_UART_RX_PIN                     GPIO_PIN_6
#define HALAL_RADIO_UART_RX_PORT                    GPIOD
#define HALAL_RADIO_UART_AF                         GPIO_AF7_USART2
#define HALAL_RADIO_UART_ISR                        USART2_IRQHandler

#define HALAL_STATE_ESTIMATION_MODULE_ENABLED
#define HALAL_STATE_ESTIMATION_UART_ENABLED
#define HALAL_STATE_ESTIMATION_UART_INSTANCE        USART6
#define HALAL_STATE_ESTIMATION_UART_BAUDRATE        115200
#define HALAL_STATE_ESTIMATION_UART_WORDLENGTH      UART_WORDLENGTH_8B
#define HALAL_STATE_ESTIMATION_UART_STOPBITS        UART_STOPBITS_1
#define HALAL_STATE_ESTIMATION_UART_PARITY          UART_PARITY_NONE
#define HALAL_STATE_ESTIMATION_UART_RCC_EN()        __HAL_RCC_USART6_CLK_ENABLE()
#define HALAL_STATE_ESTIMATION_UART_TX_PIN          GPIO_PIN_6
#define HALAL_STATE_ESTIMATION_UART_TX_PORT         GPIOC
#define HALAL_STATE_ESTIMATION_UART_RX_PIN          GPIO_PIN_9
#define HALAL_STATE_ESTIMATION_UART_RX_PORT         GPIOG
#define HALAL_STATE_ESTIMATION_UART_AF              GPIO_AF8_USART6
#define HALAL_STATE_ESTIMATION_UART_ISR             USART6_IRQHandler
#define HALAL_STATE_ESTIMATION_PACKET_SIZE          116

#endif