#!/usr/bin/env python3

from pathlib import Path
from jinja2 import Environment, FileSystemLoader
import argparse
import re
import os
import yaml

PROJECT_DIRECTORY = Path(__file__).resolve().parent.parent.parent
ACCEPTED_IOC_VERSION = "6"

def replace_cmake_toolchain_root(target_directory: Path):
    """
    Corrects CubeMX autogenerated toolchain setup to use CMAKE_CURRENT_LIST_DIR instead of CMAKE_SOURCE_DIR"
    This allows CubeMX generated folders to go within a subdirectory instead of at the project's root directory
    """

    gcc_arm_none_eabi = target_directory / 'cmake' / 'gcc-arm-none-eabi.cmake'
    starm_clang = target_directory / 'cmake' / 'starm-clang.cmake'

    assert gcc_arm_none_eabi.exists(), \
        "Cannot find cmake/gcc-arm-none-eabi.cmake! Ensure that CMake is selected as the CubeMX build system, " \
        "or update this script if needed."
    
    assert starm_clang.exists(), \
        "Cannot find cmake/gcc-arm-none-eabi.cmake! Ensure that CMake is selected as the CubeMX build system, " \
        "or update this script if needed."
    
    for file in (gcc_arm_none_eabi, starm_clang):
        file_text = file.read_text()
        assert file_text.count("{CMAKE_SOURCE_DIR}") == 1 or file_text.count("{CMAKE_CURRENT_LIST_DIR}/..") == 1, \
            f'Expected to find exactly one instance of "CMAKE_SOURCE_DIR" in {file.name}! ' \
            'Note that if CubeMX has updated their CMake template, you may need to update this script.'

        fixed_text = file_text.replace("{CMAKE_SOURCE_DIR}", "{CMAKE_CURRENT_LIST_DIR}/..")
        file.write_text(fixed_text)

def remove_isr(filepath: Path, isr_name: str):
    """
    Removes the function definition void isr_name(void) {...} from filepath
    """
    with open(filepath, "r", encoding="utf-8") as f:
        source = f.read()

    # matches "void isr_name(void) {"
    match = re.search(
        rf"\bvoid\s+{re.escape(isr_name)}\s*\(\s*(?:void)?\s*\)\s*\{{",
        source,
    )

    if not match:
        print(f"ISR {isr_name} not found, skipping.")
        return

    depth = 1
    i = match.end()

    while i < len(source) and depth:
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
        i += 1

    if depth != 0:
        raise ValueError(f"Could not find end of function {isr_name}")

    replacement = f"// {isr_name} removed by lib/scripts/fix_cubemx_autogen.py"

    body = source[match.end():(i-1)]
    non_comment_body = re.sub(rf"\/\/[\s\S]*?\r?\n|\/\*[\s\S]*?\*\/|\s", '', body)

    if len(non_comment_body) > 0:
        raise ValueError(f"Function {isr_name} contains non-comment text! Aborting. Non-comment text detected:\n{non_comment_body}")

    source = source[:match.start()] + replacement + source[i:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(source)

def find_single_file_glob(directory: Path, glob: str):
    files = list(directory.glob(glob))

    if len(files) > 1:
        raise RuntimeError(f"Found multiple {glob} files: {files}")

    if not files:
        raise FileNotFoundError(f"No {glob} file found in {directory}")

    return files[0] 

def parse_ioc(source: str):
    config = {}
    for line in source.splitlines():
        line = line.strip()
        if not line or line.startswith('#'): 
            continue
        if '=' in line:
            key, val = line.split('=', 1)
            config[key.strip()] = val.strip()
        else:
            print(f"Warning: failed to parse line\n {line}\n")

    version = config["File.Version"]

    if version != ACCEPTED_IOC_VERSION:
        raise ValueError(f"Incorrect ioc file version detcted. Expected {ACCEPTED_IOC_VERSION}, got {version}")

    return config

def autogen_platform(directory: Path):
    platform_yaml_file = find_single_file_glob(directory, "platform.yaml")
    with open(platform_yaml_file, "r", encoding="utf-8") as f:
        platform = yaml.safe_load(f)
    
    ioc_file = find_single_file_glob(directory, "*.ioc")
    with open(ioc_file, "r", encoding="utf-8") as f:
        ioc = parse_ioc(f.read())

    autogen_config = {
        "platform": platform,
        "ioc": ioc,
        "target_dir": str(directory)
    }
    
    to_render = [
        {
            "template": Path("scripts") / "port.h.jinja",
            "dest": directory / "Core" / "Inc" / "port.h",
        },
        {
            "template": Path("scripts") / "init.resc.jinja",
            "dest": directory / "init.resc",
        },
        {
            "template": Path("scripts") / "robot_config.yaml.jinja",
            "dest": directory / "robot_config.yaml",
        },
    ]

    env = Environment(loader=FileSystemLoader(os.getcwd()))
    env.globals.update(autogen_config)

    for item in to_render:
        template = env.get_template(str(item["template"]))
        rendered = template.render()
        with open(item["dest"], "w", encoding="utf-8") as f:
            f.write(rendered)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='Fix-CubeMX-CMake',
        description="Corrects CubeMX autogenerated code to correct incompatibilities with the flight-software codebase",
        epilog="This program must be re-run each time a CubeMX project is regenerated"
    )
    parser.add_argument(
        'target_directory', 
        help='Path to the directory generated by CubeMX (for example, targets/Nucleo-h723zg)',
        type=Path
    )
    args = parser.parse_args()

    replace_cmake_toolchain_root(args.target_directory)
    stm32_it_file = find_single_file_glob(args.target_directory / "Core" / "Src", "stm32*_it.c")
    print(f"Discovered STM32 interrupt file {stm32_it_file}")
    for isr in ["PendSV_Handler", "SVC_Handler", "SysTick_Handler"]:
        print(f"Removing ISR {isr}...")
        remove_isr(stm32_it_file, isr) 

    autogen_platform(args.target_directory)

    print("Done")
