#!/usr/bin/env python3

from pathlib import Path
import argparse
import re
import os

PROJECT_DIRECTORY = Path(__file__).resolve().parent.parent.parent

def replace_cmake_toolchain_root(target_directory: Path):
    """
    Corrects CubeMX autogenerated toolchain setup to use CMAKE_CURRENT_LIST_DIR instead of CMAKE_SOURCE_DIR"
    This allows CubeMX generated folders to go within a subdirectory instead of at the project's root directory
    """

    gcc_arm_none_eabi = target_directory / 'cmake' / 'gcc-arm-none-eabi.cmake'
    starm_clang = target_directory / 'cmake' / 'starm-clang.cmake'

    assert gcc_arm_none_eabi.exists(), \
        "Cannot find cmake/gcc-arm-none-eabi.cmake! Ensure that CMake is selected as the CubeMX build system, " \
        "or update this script if needed."
    
    assert starm_clang.exists(), \
        "Cannot find cmake/gcc-arm-none-eabi.cmake! Ensure that CMake is selected as the CubeMX build system, " \
        "or update this script if needed."
    
    for file in (gcc_arm_none_eabi, starm_clang):
        file_text = file.read_text()
        assert file_text.count("{CMAKE_SOURCE_DIR}") == 1 or file_text.count("{CMAKE_CURRENT_LIST_DIR}/..") == 1, \
            f'Expected to find exactly one instance of "CMAKE_SOURCE_DIR" in {file.name}! ' \
            'Note that if CubeMX has updated their CMake template, you may need to update this script.'

        fixed_text = file_text.replace("{CMAKE_SOURCE_DIR}", "{CMAKE_CURRENT_LIST_DIR}/..")
        file.write_text(fixed_text)

def remove_isr(filepath: os.PathLike, isr_name: str):
    """
    Removes the function definition void isr_name(void) {...} from filepath
    """
    with open(filepath, "r", encoding="utf-8") as f:
        source = f.read()

    # matches "void isr_name(void) {"
    match = re.search(
        rf"\bvoid\s+{re.escape(isr_name)}\s*\(\s*(?:void)?\s*\)\s*\{{",
        source,
    )

    if not match:
        print(f"ISR {isr_name} not found, skipping.")
        return

    depth = 1
    i = match.end()

    while i < len(source) and depth:
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
        i += 1

    if depth != 0:
        raise ValueError(f"Could not find end of function {isr_name}")

    replacement = f"// {isr_name} removed by lib/scripts/fix_cubemx_autogen.py"

    body = source[match.end():(i-1)]
    non_comment_body = re.sub(rf"\/\/[\s\S]*?\r?\n|\/\*[\s\S]*?\*\/|\s", '', body)

    if len(non_comment_body) > 0:
        raise ValueError(f"Function {isr_name} contains non-comment text! Aborting. Non-comment text detected:\n{non_comment_body}")

    source = source[:match.start()] + replacement + source[i:]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(source)


def find_stm32_it_file(directory: str) -> Path:
    """
    Finds the corresponding stm32_*it.c file under the target's source directory.
    Errors if there is not exactly 1 file matching the glob pattern in Core/Src/
    """

    files = list(Path(directory).glob("Core/Src/stm32*_it.c"))

    if len(files) > 1:
        raise RuntimeError(f"Found multiple stm32*_it.c files: {files}")

    if not files:
        raise FileNotFoundError(f"No stm32*_it.c file found in {directory}")

    return files[0]

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='Fix-CubeMX-CMake',
        description="Corrects CubeMX autogenerated code to correct incompatibilities with the flight-software codebase",
        epilog="This program must be re-run each time a CubeMX project is regenerated"
    )
    parser.add_argument(
        'target_directory', 
        help='Path to the directory generated by CubeMX (for example, targets/Nucleo-h723zg)',
        type=Path
    )
    args = parser.parse_args()

    replace_cmake_toolchain_root(args.target_directory)
    stm32_it_file = find_stm32_it_file(args.target_directory)
    print(f"Discovered STM32 interrupt file {stm32_it_file}")
    for isr in ["PendSV_Handler", "SVC_Handler", "SysTick_Handler"]:
        print(f"Removing ISR {isr}...")
        remove_isr(stm32_it_file, isr) 

    print("Done")
