/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKFATFS_SD_H
#define _MOCKFATFS_SD_H

#include "unity.h"
#include "stdint.h"
#include "stdbool.h"
#include "fatfs_sd.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockfatfs_sd_Init(void);
void Mockfatfs_sd_Destroy(void);
void Mockfatfs_sd_Verify(void);




#define SD_disk_initialize_ExpectAnyArgs() TEST_FAIL_MESSAGE("SD_disk_initialize requires _ExpectAnyArgsAndReturn");
#define SD_disk_initialize_ExpectAnyArgsAndReturn(cmock_retval) SD_disk_initialize_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SD_disk_initialize_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DSTATUS cmock_to_return);
#define SD_disk_initialize_Expect(pdrv) TEST_FAIL_MESSAGE("SD_disk_initialize requires _ExpectAndReturn");
#define SD_disk_initialize_ExpectAndReturn(pdrv, cmock_retval) SD_disk_initialize_CMockExpectAndReturn(__LINE__, pdrv, cmock_retval)
void SD_disk_initialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, DSTATUS cmock_to_return);
typedef DSTATUS (* CMOCK_SD_disk_initialize_CALLBACK)(BYTE pdrv, int cmock_num_calls);
void SD_disk_initialize_AddCallback(CMOCK_SD_disk_initialize_CALLBACK Callback);
void SD_disk_initialize_Stub(CMOCK_SD_disk_initialize_CALLBACK Callback);
#define SD_disk_initialize_StubWithCallback SD_disk_initialize_Stub
#define SD_disk_status_ExpectAnyArgs() TEST_FAIL_MESSAGE("SD_disk_status requires _ExpectAnyArgsAndReturn");
#define SD_disk_status_ExpectAnyArgsAndReturn(cmock_retval) SD_disk_status_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SD_disk_status_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DSTATUS cmock_to_return);
#define SD_disk_status_Expect(pdrv) TEST_FAIL_MESSAGE("SD_disk_status requires _ExpectAndReturn");
#define SD_disk_status_ExpectAndReturn(pdrv, cmock_retval) SD_disk_status_CMockExpectAndReturn(__LINE__, pdrv, cmock_retval)
void SD_disk_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, DSTATUS cmock_to_return);
typedef DSTATUS (* CMOCK_SD_disk_status_CALLBACK)(BYTE pdrv, int cmock_num_calls);
void SD_disk_status_AddCallback(CMOCK_SD_disk_status_CALLBACK Callback);
void SD_disk_status_Stub(CMOCK_SD_disk_status_CALLBACK Callback);
#define SD_disk_status_StubWithCallback SD_disk_status_Stub
#define SD_disk_read_ExpectAnyArgs() TEST_FAIL_MESSAGE("SD_disk_read requires _ExpectAnyArgsAndReturn");
#define SD_disk_read_ExpectAnyArgsAndReturn(cmock_retval) SD_disk_read_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SD_disk_read_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DRESULT cmock_to_return);
#define SD_disk_read_Expect(pdrv, buff, sector, count) TEST_FAIL_MESSAGE("SD_disk_read requires _ExpectAndReturn");
#define SD_disk_read_ExpectAndReturn(pdrv, buff, sector, count, cmock_retval) SD_disk_read_CMockExpectAndReturn(__LINE__, pdrv, buff, sector, count, cmock_retval)
void SD_disk_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, BYTE* buff, DWORD sector, UINT count, DRESULT cmock_to_return);
typedef DRESULT (* CMOCK_SD_disk_read_CALLBACK)(BYTE pdrv, BYTE* buff, DWORD sector, UINT count, int cmock_num_calls);
void SD_disk_read_AddCallback(CMOCK_SD_disk_read_CALLBACK Callback);
void SD_disk_read_Stub(CMOCK_SD_disk_read_CALLBACK Callback);
#define SD_disk_read_StubWithCallback SD_disk_read_Stub
#define SD_disk_read_ReturnThruPtr_buff(buff) SD_disk_read_CMockReturnMemThruPtr_buff(__LINE__, buff, sizeof(BYTE))
#define SD_disk_read_ReturnArrayThruPtr_buff(buff, cmock_len) SD_disk_read_CMockReturnMemThruPtr_buff(__LINE__, buff, (cmock_len * sizeof(*buff)))
#define SD_disk_read_ReturnMemThruPtr_buff(buff, cmock_size) SD_disk_read_CMockReturnMemThruPtr_buff(__LINE__, buff, (cmock_size))
void SD_disk_read_CMockReturnMemThruPtr_buff(UNITY_LINE_TYPE cmock_line, BYTE const* buff, size_t cmock_size);
#define SD_disk_write_ExpectAnyArgs() TEST_FAIL_MESSAGE("SD_disk_write requires _ExpectAnyArgsAndReturn");
#define SD_disk_write_ExpectAnyArgsAndReturn(cmock_retval) SD_disk_write_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SD_disk_write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DRESULT cmock_to_return);
#define SD_disk_write_Expect(pdrv, buff, sector, count) TEST_FAIL_MESSAGE("SD_disk_write requires _ExpectAndReturn");
#define SD_disk_write_ExpectAndReturn(pdrv, buff, sector, count, cmock_retval) SD_disk_write_CMockExpectAndReturn(__LINE__, pdrv, buff, sector, count, cmock_retval)
void SD_disk_write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, const BYTE* buff, DWORD sector, UINT count, DRESULT cmock_to_return);
typedef DRESULT (* CMOCK_SD_disk_write_CALLBACK)(BYTE pdrv, const BYTE* buff, DWORD sector, UINT count, int cmock_num_calls);
void SD_disk_write_AddCallback(CMOCK_SD_disk_write_CALLBACK Callback);
void SD_disk_write_Stub(CMOCK_SD_disk_write_CALLBACK Callback);
#define SD_disk_write_StubWithCallback SD_disk_write_Stub
#define SD_disk_ioctl_ExpectAnyArgs() TEST_FAIL_MESSAGE("SD_disk_ioctl requires _ExpectAnyArgsAndReturn");
#define SD_disk_ioctl_ExpectAnyArgsAndReturn(cmock_retval) SD_disk_ioctl_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SD_disk_ioctl_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DRESULT cmock_to_return);
#define SD_disk_ioctl_Expect(pdrv, cmd, buff) TEST_FAIL_MESSAGE("SD_disk_ioctl requires _ExpectAndReturn");
#define SD_disk_ioctl_ExpectAndReturn(pdrv, cmd, buff, cmock_retval) SD_disk_ioctl_CMockExpectAndReturn(__LINE__, pdrv, cmd, buff, cmock_retval)
void SD_disk_ioctl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, BYTE cmd, void* buff, DRESULT cmock_to_return);
typedef DRESULT (* CMOCK_SD_disk_ioctl_CALLBACK)(BYTE pdrv, BYTE cmd, void* buff, int cmock_num_calls);
void SD_disk_ioctl_AddCallback(CMOCK_SD_disk_ioctl_CALLBACK Callback);
void SD_disk_ioctl_Stub(CMOCK_SD_disk_ioctl_CALLBACK Callback);
#define SD_disk_ioctl_StubWithCallback SD_disk_ioctl_Stub
#define SD_disk_ioctl_ReturnThruPtr_buff(buff) SD_disk_ioctl_CMockReturnMemThruPtr_buff(__LINE__, buff, sizeof(*buff))
#define SD_disk_ioctl_ReturnArrayThruPtr_buff(buff, cmock_len) SD_disk_ioctl_CMockReturnMemThruPtr_buff(__LINE__, buff, (cmock_len * sizeof(*buff)))
#define SD_disk_ioctl_ReturnMemThruPtr_buff(buff, cmock_size) SD_disk_ioctl_CMockReturnMemThruPtr_buff(__LINE__, buff, (cmock_size))
void SD_disk_ioctl_CMockReturnMemThruPtr_buff(UNITY_LINE_TYPE cmock_line, void const* buff, size_t cmock_size);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
