/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockfatfs_sd.h"

static const char* CMockString_SD_disk_initialize = "SD_disk_initialize";
static const char* CMockString_SD_disk_ioctl = "SD_disk_ioctl";
static const char* CMockString_SD_disk_read = "SD_disk_read";
static const char* CMockString_SD_disk_status = "SD_disk_status";
static const char* CMockString_SD_disk_write = "SD_disk_write";
static const char* CMockString_buff = "buff";
static const char* CMockString_cmd = "cmd";
static const char* CMockString_count = "count";
static const char* CMockString_pdrv = "pdrv";
static const char* CMockString_sector = "sector";

typedef struct _CMOCK_SD_disk_initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  DSTATUS ReturnVal;
  BYTE Expected_pdrv;

} CMOCK_SD_disk_initialize_CALL_INSTANCE;

typedef struct _CMOCK_SD_disk_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  DSTATUS ReturnVal;
  BYTE Expected_pdrv;

} CMOCK_SD_disk_status_CALL_INSTANCE;

typedef struct _CMOCK_SD_disk_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  DRESULT ReturnVal;
  BYTE Expected_pdrv;
  BYTE* Expected_buff;
  DWORD Expected_sector;
  UINT Expected_count;
  char ReturnThruPtr_buff_Used;
  BYTE const* ReturnThruPtr_buff_Val;
  size_t ReturnThruPtr_buff_Size;

} CMOCK_SD_disk_read_CALL_INSTANCE;

typedef struct _CMOCK_SD_disk_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  DRESULT ReturnVal;
  BYTE Expected_pdrv;
  const BYTE* Expected_buff;
  DWORD Expected_sector;
  UINT Expected_count;

} CMOCK_SD_disk_write_CALL_INSTANCE;

typedef struct _CMOCK_SD_disk_ioctl_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  DRESULT ReturnVal;
  BYTE Expected_pdrv;
  BYTE Expected_cmd;
  void* Expected_buff;
  char ReturnThruPtr_buff_Used;
  void const* ReturnThruPtr_buff_Val;
  size_t ReturnThruPtr_buff_Size;

} CMOCK_SD_disk_ioctl_CALL_INSTANCE;

static struct Mockfatfs_sdInstance
{
  char SD_disk_initialize_CallbackBool;
  CMOCK_SD_disk_initialize_CALLBACK SD_disk_initialize_CallbackFunctionPointer;
  int SD_disk_initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SD_disk_initialize_CallInstance;
  char SD_disk_status_CallbackBool;
  CMOCK_SD_disk_status_CALLBACK SD_disk_status_CallbackFunctionPointer;
  int SD_disk_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SD_disk_status_CallInstance;
  char SD_disk_read_CallbackBool;
  CMOCK_SD_disk_read_CALLBACK SD_disk_read_CallbackFunctionPointer;
  int SD_disk_read_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SD_disk_read_CallInstance;
  char SD_disk_write_CallbackBool;
  CMOCK_SD_disk_write_CALLBACK SD_disk_write_CallbackFunctionPointer;
  int SD_disk_write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SD_disk_write_CallInstance;
  char SD_disk_ioctl_CallbackBool;
  CMOCK_SD_disk_ioctl_CALLBACK SD_disk_ioctl_CallbackFunctionPointer;
  int SD_disk_ioctl_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SD_disk_ioctl_CallInstance;
} Mock;


void Mockfatfs_sd_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.SD_disk_initialize_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_initialize);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SD_disk_initialize_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SD_disk_status_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_status);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SD_disk_status_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SD_disk_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SD_disk_read_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SD_disk_write_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SD_disk_write_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SD_disk_ioctl_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_ioctl);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SD_disk_ioctl_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockfatfs_sd_Init(void)
{
  Mockfatfs_sd_Destroy();
}

void Mockfatfs_sd_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

DSTATUS SD_disk_initialize(BYTE pdrv)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SD_disk_initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SD_disk_initialize);
  cmock_call_instance = (CMOCK_SD_disk_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SD_disk_initialize_CallInstance);
  Mock.SD_disk_initialize_CallInstance = CMock_Guts_MemNext(Mock.SD_disk_initialize_CallInstance);
  if (!Mock.SD_disk_initialize_CallbackBool &&
      Mock.SD_disk_initialize_CallbackFunctionPointer != NULL)
  {
    DSTATUS cmock_cb_ret = Mock.SD_disk_initialize_CallbackFunctionPointer(pdrv, Mock.SD_disk_initialize_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_initialize,CMockString_pdrv);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_pdrv, &pdrv, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SD_disk_initialize_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_initialize);
    cmock_call_instance->ReturnVal = Mock.SD_disk_initialize_CallbackFunctionPointer(pdrv, Mock.SD_disk_initialize_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SD_disk_initialize(CMOCK_SD_disk_initialize_CALL_INSTANCE* cmock_call_instance, BYTE pdrv);
void CMockExpectParameters_SD_disk_initialize(CMOCK_SD_disk_initialize_CALL_INSTANCE* cmock_call_instance, BYTE pdrv)
{
  memcpy((void*)(&cmock_call_instance->Expected_pdrv), (const void*)(&pdrv),
         sizeof(BYTE[sizeof(pdrv) == sizeof(BYTE) ? 1 : -1])); /* add BYTE to :treat_as_array if this causes an error */
}

void SD_disk_initialize_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DSTATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_initialize_CALL_INSTANCE));
  CMOCK_SD_disk_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_initialize_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_initialize_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SD_disk_initialize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, DSTATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_initialize_CALL_INSTANCE));
  CMOCK_SD_disk_initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_initialize_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_initialize_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SD_disk_initialize(cmock_call_instance, pdrv);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(DSTATUS[sizeof(cmock_to_return) == sizeof(DSTATUS) ? 1 : -1])); /* add DSTATUS to :treat_as_array if this causes an error */
}

void SD_disk_initialize_AddCallback(CMOCK_SD_disk_initialize_CALLBACK Callback)
{
  Mock.SD_disk_initialize_CallbackBool = (char)1;
  Mock.SD_disk_initialize_CallbackFunctionPointer = Callback;
}

void SD_disk_initialize_Stub(CMOCK_SD_disk_initialize_CALLBACK Callback)
{
  Mock.SD_disk_initialize_CallbackBool = (char)0;
  Mock.SD_disk_initialize_CallbackFunctionPointer = Callback;
}

DSTATUS SD_disk_status(BYTE pdrv)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SD_disk_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SD_disk_status);
  cmock_call_instance = (CMOCK_SD_disk_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SD_disk_status_CallInstance);
  Mock.SD_disk_status_CallInstance = CMock_Guts_MemNext(Mock.SD_disk_status_CallInstance);
  if (!Mock.SD_disk_status_CallbackBool &&
      Mock.SD_disk_status_CallbackFunctionPointer != NULL)
  {
    DSTATUS cmock_cb_ret = Mock.SD_disk_status_CallbackFunctionPointer(pdrv, Mock.SD_disk_status_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_status,CMockString_pdrv);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_pdrv, &pdrv, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SD_disk_status_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_status);
    cmock_call_instance->ReturnVal = Mock.SD_disk_status_CallbackFunctionPointer(pdrv, Mock.SD_disk_status_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SD_disk_status(CMOCK_SD_disk_status_CALL_INSTANCE* cmock_call_instance, BYTE pdrv);
void CMockExpectParameters_SD_disk_status(CMOCK_SD_disk_status_CALL_INSTANCE* cmock_call_instance, BYTE pdrv)
{
  memcpy((void*)(&cmock_call_instance->Expected_pdrv), (const void*)(&pdrv),
         sizeof(BYTE[sizeof(pdrv) == sizeof(BYTE) ? 1 : -1])); /* add BYTE to :treat_as_array if this causes an error */
}

void SD_disk_status_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DSTATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_status_CALL_INSTANCE));
  CMOCK_SD_disk_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_status_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SD_disk_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, DSTATUS cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_status_CALL_INSTANCE));
  CMOCK_SD_disk_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_status_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SD_disk_status(cmock_call_instance, pdrv);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(DSTATUS[sizeof(cmock_to_return) == sizeof(DSTATUS) ? 1 : -1])); /* add DSTATUS to :treat_as_array if this causes an error */
}

void SD_disk_status_AddCallback(CMOCK_SD_disk_status_CALLBACK Callback)
{
  Mock.SD_disk_status_CallbackBool = (char)1;
  Mock.SD_disk_status_CallbackFunctionPointer = Callback;
}

void SD_disk_status_Stub(CMOCK_SD_disk_status_CALLBACK Callback)
{
  Mock.SD_disk_status_CallbackBool = (char)0;
  Mock.SD_disk_status_CallbackFunctionPointer = Callback;
}

DRESULT SD_disk_read(BYTE pdrv, BYTE* buff, DWORD sector, UINT count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SD_disk_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SD_disk_read);
  cmock_call_instance = (CMOCK_SD_disk_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SD_disk_read_CallInstance);
  Mock.SD_disk_read_CallInstance = CMock_Guts_MemNext(Mock.SD_disk_read_CallInstance);
  if (!Mock.SD_disk_read_CallbackBool &&
      Mock.SD_disk_read_CallbackFunctionPointer != NULL)
  {
    DRESULT cmock_cb_ret = Mock.SD_disk_read_CallbackFunctionPointer(pdrv, buff, sector, count, Mock.SD_disk_read_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_read,CMockString_pdrv);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_pdrv, &pdrv, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_read,CMockString_buff);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_buff, buff, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_read,CMockString_sector);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_sector, &sector, sizeof(DWORD), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_read,CMockString_count);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_count, &count, sizeof(UINT), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SD_disk_read_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_read);
    cmock_call_instance->ReturnVal = Mock.SD_disk_read_CallbackFunctionPointer(pdrv, buff, sector, count, Mock.SD_disk_read_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buff_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buff, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buff, (const void*)cmock_call_instance->ReturnThruPtr_buff_Val,
      cmock_call_instance->ReturnThruPtr_buff_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SD_disk_read(CMOCK_SD_disk_read_CALL_INSTANCE* cmock_call_instance, BYTE pdrv, BYTE* buff, DWORD sector, UINT count);
void CMockExpectParameters_SD_disk_read(CMOCK_SD_disk_read_CALL_INSTANCE* cmock_call_instance, BYTE pdrv, BYTE* buff, DWORD sector, UINT count)
{
  memcpy((void*)(&cmock_call_instance->Expected_pdrv), (const void*)(&pdrv),
         sizeof(BYTE[sizeof(pdrv) == sizeof(BYTE) ? 1 : -1])); /* add BYTE to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buff = buff;
  cmock_call_instance->ReturnThruPtr_buff_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_sector), (const void*)(&sector),
         sizeof(DWORD[sizeof(sector) == sizeof(DWORD) ? 1 : -1])); /* add DWORD to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_count), (const void*)(&count),
         sizeof(UINT[sizeof(count) == sizeof(UINT) ? 1 : -1])); /* add UINT to :treat_as_array if this causes an error */
}

void SD_disk_read_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DRESULT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_read_CALL_INSTANCE));
  CMOCK_SD_disk_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_read_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SD_disk_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, BYTE* buff, DWORD sector, UINT count, DRESULT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_read_CALL_INSTANCE));
  CMOCK_SD_disk_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_read_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SD_disk_read(cmock_call_instance, pdrv, buff, sector, count);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(DRESULT[sizeof(cmock_to_return) == sizeof(DRESULT) ? 1 : -1])); /* add DRESULT to :treat_as_array if this causes an error */
}

void SD_disk_read_AddCallback(CMOCK_SD_disk_read_CALLBACK Callback)
{
  Mock.SD_disk_read_CallbackBool = (char)1;
  Mock.SD_disk_read_CallbackFunctionPointer = Callback;
}

void SD_disk_read_Stub(CMOCK_SD_disk_read_CALLBACK Callback)
{
  Mock.SD_disk_read_CallbackBool = (char)0;
  Mock.SD_disk_read_CallbackFunctionPointer = Callback;
}

void SD_disk_read_CMockReturnMemThruPtr_buff(UNITY_LINE_TYPE cmock_line, BYTE const* buff, size_t cmock_size)
{
  CMOCK_SD_disk_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SD_disk_read_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buff_Used = 1;
  cmock_call_instance->ReturnThruPtr_buff_Val = buff;
  cmock_call_instance->ReturnThruPtr_buff_Size = cmock_size;
}

DRESULT SD_disk_write(BYTE pdrv, const BYTE* buff, DWORD sector, UINT count)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SD_disk_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SD_disk_write);
  cmock_call_instance = (CMOCK_SD_disk_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SD_disk_write_CallInstance);
  Mock.SD_disk_write_CallInstance = CMock_Guts_MemNext(Mock.SD_disk_write_CallInstance);
  if (!Mock.SD_disk_write_CallbackBool &&
      Mock.SD_disk_write_CallbackFunctionPointer != NULL)
  {
    DRESULT cmock_cb_ret = Mock.SD_disk_write_CallbackFunctionPointer(pdrv, buff, sector, count, Mock.SD_disk_write_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_write,CMockString_pdrv);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_pdrv, &pdrv, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_write,CMockString_buff);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(cmock_call_instance->Expected_buff, buff, sizeof(const BYTE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_write,CMockString_sector);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_sector, &sector, sizeof(DWORD), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_write,CMockString_count);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_count, &count, sizeof(UINT), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.SD_disk_write_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_write);
    cmock_call_instance->ReturnVal = Mock.SD_disk_write_CallbackFunctionPointer(pdrv, buff, sector, count, Mock.SD_disk_write_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SD_disk_write(CMOCK_SD_disk_write_CALL_INSTANCE* cmock_call_instance, BYTE pdrv, const BYTE* buff, DWORD sector, UINT count);
void CMockExpectParameters_SD_disk_write(CMOCK_SD_disk_write_CALL_INSTANCE* cmock_call_instance, BYTE pdrv, const BYTE* buff, DWORD sector, UINT count)
{
  memcpy((void*)(&cmock_call_instance->Expected_pdrv), (const void*)(&pdrv),
         sizeof(BYTE[sizeof(pdrv) == sizeof(BYTE) ? 1 : -1])); /* add BYTE to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buff = buff;
  memcpy((void*)(&cmock_call_instance->Expected_sector), (const void*)(&sector),
         sizeof(DWORD[sizeof(sector) == sizeof(DWORD) ? 1 : -1])); /* add DWORD to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_count), (const void*)(&count),
         sizeof(UINT[sizeof(count) == sizeof(UINT) ? 1 : -1])); /* add UINT to :treat_as_array if this causes an error */
}

void SD_disk_write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DRESULT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_write_CALL_INSTANCE));
  CMOCK_SD_disk_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_write_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SD_disk_write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, const BYTE* buff, DWORD sector, UINT count, DRESULT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_write_CALL_INSTANCE));
  CMOCK_SD_disk_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_write_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_write_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SD_disk_write(cmock_call_instance, pdrv, buff, sector, count);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(DRESULT[sizeof(cmock_to_return) == sizeof(DRESULT) ? 1 : -1])); /* add DRESULT to :treat_as_array if this causes an error */
}

void SD_disk_write_AddCallback(CMOCK_SD_disk_write_CALLBACK Callback)
{
  Mock.SD_disk_write_CallbackBool = (char)1;
  Mock.SD_disk_write_CallbackFunctionPointer = Callback;
}

void SD_disk_write_Stub(CMOCK_SD_disk_write_CALLBACK Callback)
{
  Mock.SD_disk_write_CallbackBool = (char)0;
  Mock.SD_disk_write_CallbackFunctionPointer = Callback;
}

DRESULT SD_disk_ioctl(BYTE pdrv, BYTE cmd, void* buff)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SD_disk_ioctl_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SD_disk_ioctl);
  cmock_call_instance = (CMOCK_SD_disk_ioctl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SD_disk_ioctl_CallInstance);
  Mock.SD_disk_ioctl_CallInstance = CMock_Guts_MemNext(Mock.SD_disk_ioctl_CallInstance);
  if (!Mock.SD_disk_ioctl_CallbackBool &&
      Mock.SD_disk_ioctl_CallbackFunctionPointer != NULL)
  {
    DRESULT cmock_cb_ret = Mock.SD_disk_ioctl_CallbackFunctionPointer(pdrv, cmd, buff, Mock.SD_disk_ioctl_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_ioctl,CMockString_pdrv);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_pdrv, &pdrv, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_ioctl,CMockString_cmd);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_cmd, &cmd, sizeof(BYTE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SD_disk_ioctl,CMockString_buff);
    if (cmock_call_instance->Expected_buff == NULL)
      { UNITY_TEST_ASSERT_NULL(buff, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buff, buff, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.SD_disk_ioctl_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_SD_disk_ioctl);
    cmock_call_instance->ReturnVal = Mock.SD_disk_ioctl_CallbackFunctionPointer(pdrv, cmd, buff, Mock.SD_disk_ioctl_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buff_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buff, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buff, (const void*)cmock_call_instance->ReturnThruPtr_buff_Val,
      cmock_call_instance->ReturnThruPtr_buff_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SD_disk_ioctl(CMOCK_SD_disk_ioctl_CALL_INSTANCE* cmock_call_instance, BYTE pdrv, BYTE cmd, void* buff);
void CMockExpectParameters_SD_disk_ioctl(CMOCK_SD_disk_ioctl_CALL_INSTANCE* cmock_call_instance, BYTE pdrv, BYTE cmd, void* buff)
{
  memcpy((void*)(&cmock_call_instance->Expected_pdrv), (const void*)(&pdrv),
         sizeof(BYTE[sizeof(pdrv) == sizeof(BYTE) ? 1 : -1])); /* add BYTE to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_cmd), (const void*)(&cmd),
         sizeof(BYTE[sizeof(cmd) == sizeof(BYTE) ? 1 : -1])); /* add BYTE to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buff = buff;
  cmock_call_instance->ReturnThruPtr_buff_Used = 0;
}

void SD_disk_ioctl_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DRESULT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_ioctl_CALL_INSTANCE));
  CMOCK_SD_disk_ioctl_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_ioctl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_ioctl_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_ioctl_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void SD_disk_ioctl_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, BYTE pdrv, BYTE cmd, void* buff, DRESULT cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SD_disk_ioctl_CALL_INSTANCE));
  CMOCK_SD_disk_ioctl_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_ioctl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SD_disk_ioctl_CallInstance = CMock_Guts_MemChain(Mock.SD_disk_ioctl_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_SD_disk_ioctl(cmock_call_instance, pdrv, cmd, buff);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (const void*)(&cmock_to_return),
         sizeof(DRESULT[sizeof(cmock_to_return) == sizeof(DRESULT) ? 1 : -1])); /* add DRESULT to :treat_as_array if this causes an error */
}

void SD_disk_ioctl_AddCallback(CMOCK_SD_disk_ioctl_CALLBACK Callback)
{
  Mock.SD_disk_ioctl_CallbackBool = (char)1;
  Mock.SD_disk_ioctl_CallbackFunctionPointer = Callback;
}

void SD_disk_ioctl_Stub(CMOCK_SD_disk_ioctl_CALLBACK Callback)
{
  Mock.SD_disk_ioctl_CallbackBool = (char)0;
  Mock.SD_disk_ioctl_CallbackFunctionPointer = Callback;
}

void SD_disk_ioctl_CMockReturnMemThruPtr_buff(UNITY_LINE_TYPE cmock_line, void const* buff, size_t cmock_size)
{
  CMOCK_SD_disk_ioctl_CALL_INSTANCE* cmock_call_instance = (CMOCK_SD_disk_ioctl_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SD_disk_ioctl_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buff_Used = 1;
  cmock_call_instance->ReturnThruPtr_buff_Val = buff;
  cmock_call_instance->ReturnThruPtr_buff_Size = cmock_size;
}

