/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKCOMMANDS_H
#define _MOCKCOMMANDS_H

#include "unity.h"
#include "stdint.h"
#include "stdbool.h"
#include "commands.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockcommands_Init(void);
void Mockcommands_Destroy(void);
void Mockcommands_Verify(void);




#define process_command_ExpectAnyArgs() TEST_FAIL_MESSAGE("process_command requires _ExpectAnyArgsAndReturn");
#define process_command_ExpectAnyArgsAndReturn(cmock_retval) process_command_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void process_command_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define process_command_Expect(command_id) TEST_FAIL_MESSAGE("process_command requires _ExpectAndReturn");
#define process_command_ExpectAndReturn(command_id, cmock_retval) process_command_CMockExpectAndReturn(__LINE__, command_id, cmock_retval)
void process_command_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t command_id, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_process_command_CALLBACK)(uint8_t command_id, int cmock_num_calls);
void process_command_AddCallback(CMOCK_process_command_CALLBACK Callback);
void process_command_Stub(CMOCK_process_command_CALLBACK Callback);
#define process_command_StubWithCallback process_command_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
