/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockcommands.h"

static const char* CMockString_command_id = "command_id";
static const char* CMockString_process_command = "process_command";

typedef struct _CMOCK_process_command_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t ReturnVal;
  uint8_t Expected_command_id;

} CMOCK_process_command_CALL_INSTANCE;

static struct MockcommandsInstance
{
  char process_command_CallbackBool;
  CMOCK_process_command_CALLBACK process_command_CallbackFunctionPointer;
  int process_command_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE process_command_CallInstance;
} Mock;


void Mockcommands_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.process_command_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_process_command);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.process_command_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockcommands_Init(void)
{
  Mockcommands_Destroy();
}

void Mockcommands_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint8_t process_command(uint8_t command_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_process_command_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_process_command);
  cmock_call_instance = (CMOCK_process_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.process_command_CallInstance);
  Mock.process_command_CallInstance = CMock_Guts_MemNext(Mock.process_command_CallInstance);
  if (!Mock.process_command_CallbackBool &&
      Mock.process_command_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.process_command_CallbackFunctionPointer(command_id, Mock.process_command_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_process_command,CMockString_command_id);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_command_id, command_id, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.process_command_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_process_command);
    cmock_call_instance->ReturnVal = Mock.process_command_CallbackFunctionPointer(command_id, Mock.process_command_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_process_command(CMOCK_process_command_CALL_INSTANCE* cmock_call_instance, uint8_t command_id);
void CMockExpectParameters_process_command(CMOCK_process_command_CALL_INSTANCE* cmock_call_instance, uint8_t command_id)
{
  cmock_call_instance->Expected_command_id = command_id;
}

void process_command_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_process_command_CALL_INSTANCE));
  CMOCK_process_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_process_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.process_command_CallInstance = CMock_Guts_MemChain(Mock.process_command_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void process_command_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t command_id, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_process_command_CALL_INSTANCE));
  CMOCK_process_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_process_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.process_command_CallInstance = CMock_Guts_MemChain(Mock.process_command_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_process_command(cmock_call_instance, command_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void process_command_AddCallback(CMOCK_process_command_CALLBACK Callback)
{
  Mock.process_command_CallbackBool = (char)1;
  Mock.process_command_CallbackFunctionPointer = Callback;
}

void process_command_Stub(CMOCK_process_command_CALLBACK Callback)
{
  Mock.process_command_CallbackBool = (char)0;
  Mock.process_command_CallbackFunctionPointer = Callback;
}

