#!/usr/bin/env python3

from pathlib import Path
import argparse

PROJECT_DIRECTORY = Path(__file__).resolve().parent.parent.parent

def replace_cmake_toolchain_root(target_directory: Path):
    """
    Corrects CubeMX autogenerated toolchain setup to use CMAKE_CURRENT_LIST_DIR instead of CMAKE_SOURCE_DIR"
    This allows CubeMX generated folders to go within a subdirectory instead of at the project's root directory
    """

    gcc_arm_none_eabi = target_directory / 'cmake' / 'gcc-arm-none-eabi.cmake'
    starm_clang = target_directory / 'cmake' / 'starm-clang.cmake'

    assert gcc_arm_none_eabi.exists(), \
        "Cannot find cmake/gcc-arm-none-eabi.cmake! Ensure that CMake is selected as the CubeMX build system, " \
        "or update this script if needed."
    
    assert starm_clang.exists(), \
        "Cannot find cmake/gcc-arm-none-eabi.cmake! Ensure that CMake is selected as the CubeMX build system, " \
        "or update this script if needed."
    
    for file in (gcc_arm_none_eabi, starm_clang):
        file_text = file.read_text()
        assert file_text.count("{CMAKE_SOURCE_DIR}") == 1 or file_text.count("{CMAKE_CURRENT_LIST_DIR}/..") == 1, \
            f'Expected to find exactly one instance of "CMAKE_SOURCE_DIR" in {file.name}! ' \
            'Note that if CubeMX has updated their CMake template, you may need to update this script.'

        fixed_text = file_text.replace("{CMAKE_SOURCE_DIR}", "{CMAKE_CURRENT_LIST_DIR}/..")
        file.write_text(fixed_text)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='Fix-CubeMX-CMake',
        description="Corrects CubeMX autogenerated code to correct incompatibilities with the flight-software codebase",
        epilog="This program must be re-run each time a CubeMX project is regenerated"
    )
    parser.add_argument(
        'target_directory', 
        help='Path to the directory generated by CubeMX (for example, targets/Nucleo-h723zg)',
        type=Path
    )
    args = parser.parse_args()

    replace_cmake_toolchain_root(args.target_directory)

    print("Done")
