#ifndef PROTOCOL_H
#define PROTOCOL_H

#include <time.h>
#include <stdbool.h>
#include <stdint.h>

// Uncomment this line to include SQL macros
//#define INCLUDE_PROTOCOL_SQL_MACROS

//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************
// DISCLAIMER: THIS FILE WAS AUTO-GENERATED BY protocol_generator.py
// DO NOT MODIFY THIS FILE DIRECTLY!
// TO MODIFY THE PROTOCOL, EDIT protocol.json AND RE-RUN protocol_generator.py
//****************************************************************************************************
//****************************************************************************************************
//****************************************************************************************************


#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	void generate_sql_timestamp_from_long(time_t time, char* buffer);
	#define WEB_SERVER_URL "http://0.0.0.0:8080"
#endif

struct RocketKinematics {
	float attitude_w;
	float attitude_x;
	float attitude_y;
	float attitude_z;
	int velocity;
	time_t timestamp;
};
#define ROCKETKINEMATICS_MSG_ID 2
#define ROCKETKINEMATICS_SIZE sizeof(struct RocketKinematics)
#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define ROCKETKINEMATICS_SQL_TABLE_GEN "CREATE TABLE RocketKinematics ( " \
		"attitude_w real," \
		"attitude_x real," \
		"attitude_y real," \
		"attitude_z real," \
		"velocity int," \
		"time datetime PRIMARY KEY);"
	#define ROCKETKINEMATICS_SQL_GET_MOST_RECENT "SELECT TOP 1 attitude_w, attitude_x, attitude_y, attitude_z, velocity, time FROM RocketKinematics ORDER BY time"
	#define ROCKETKINEMATICS_SQL_ADD_ENTRY(buffer, data, timestamp) sprintf(buffer, \
		"INSERT INTO RocketKinematics VALUES ('%.10E', '%.10E', '%.10E', '%.10E', '%d', '%s');", \
		data->attitude_w, \
		data->attitude_x, \
		data->attitude_y, \
		data->attitude_z, \
		data->velocity, \
		timestamp); 
	#define ROCKETKINEMATICS_API_PATH WEB_SERVER_URL "/api/data/RocketKinematics"
	#define ROCKETKINEMATICS_SQL_SELECT_TO_JSON(sql_row_values) "{ %m: %s, %m: %s, %m: %s, %m: %s, %m: %s, %m: %s }", \
			MG_ESC("attitude_w"), sql_row_values[0], \
			MG_ESC("attitude_x"), sql_row_values[1], \
			MG_ESC("attitude_y"), sql_row_values[2], \
			MG_ESC("attitude_z"), sql_row_values[3], \
			MG_ESC("velocity"), sql_row_values[4], \
			MG_ESC("timestamp"), sql_row_values[5]
#endif

struct MasterElectric {
	float voltage;
	float current;
	int electricity_status;
	time_t timestamp;
};
#define MASTERELECTRIC_MSG_ID 3
#define MASTERELECTRIC_SIZE sizeof(struct MasterElectric)
#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define MASTERELECTRIC_SQL_TABLE_GEN "CREATE TABLE MasterElectric ( " \
		"voltage real," \
		"current real," \
		"electricity_status int," \
		"time datetime PRIMARY KEY);"
	#define MASTERELECTRIC_SQL_GET_MOST_RECENT "SELECT TOP 1 voltage, current, electricity_status, time FROM MasterElectric ORDER BY time"
	#define MASTERELECTRIC_SQL_ADD_ENTRY(buffer, data, timestamp) sprintf(buffer, \
		"INSERT INTO MasterElectric VALUES ('%.10E', '%.10E', '%d', '%s');", \
		data->voltage, \
		data->current, \
		data->electricity_status, \
		timestamp); 
	#define MASTERELECTRIC_API_PATH WEB_SERVER_URL "/api/data/MasterElectric"
	#define MASTERELECTRIC_SQL_SELECT_TO_JSON(sql_row_values) "{ %m: %s, %m: %s, %m: %s, %m: %s }", \
			MG_ESC("voltage"), sql_row_values[0], \
			MG_ESC("current"), sql_row_values[1], \
			MG_ESC("electricity_status"), sql_row_values[2], \
			MG_ESC("timestamp"), sql_row_values[3]
#endif

struct RocketState {
	int current_state;
	int health_status;
	time_t timestamp;
};
#define ROCKETSTATE_MSG_ID 4
#define ROCKETSTATE_SIZE sizeof(struct RocketState)
#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define ROCKETSTATE_SQL_TABLE_GEN "CREATE TABLE RocketState ( " \
		"current_state int," \
		"health_status int," \
		"time datetime PRIMARY KEY);"
	#define ROCKETSTATE_SQL_GET_MOST_RECENT "SELECT TOP 1 current_state, health_status, time FROM RocketState ORDER BY time"
	#define ROCKETSTATE_SQL_ADD_ENTRY(buffer, data, timestamp) sprintf(buffer, \
		"INSERT INTO RocketState VALUES ('%d', '%d', '%s');", \
		data->current_state, \
		data->health_status, \
		timestamp); 
	#define ROCKETSTATE_API_PATH WEB_SERVER_URL "/api/data/RocketState"
	#define ROCKETSTATE_SQL_SELECT_TO_JSON(sql_row_values) "{ %m: %s, %m: %s, %m: %s }", \
			MG_ESC("current_state"), sql_row_values[0], \
			MG_ESC("health_status"), sql_row_values[1], \
			MG_ESC("timestamp"), sql_row_values[2]
#endif

struct ActuatorHealths {
	float current_servo_1;
	float current_servo_2;
	float current_servo_3;
	float current_servo_4;
	time_t timestamp;
};
#define ACTUATORHEALTHS_MSG_ID 5
#define ACTUATORHEALTHS_SIZE sizeof(struct ActuatorHealths)
#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define ACTUATORHEALTHS_SQL_TABLE_GEN "CREATE TABLE ActuatorHealths ( " \
		"current_servo_1 real," \
		"current_servo_2 real," \
		"current_servo_3 real," \
		"current_servo_4 real," \
		"time datetime PRIMARY KEY);"
	#define ACTUATORHEALTHS_SQL_GET_MOST_RECENT "SELECT TOP 1 current_servo_1, current_servo_2, current_servo_3, current_servo_4, time FROM ActuatorHealths ORDER BY time"
	#define ACTUATORHEALTHS_SQL_ADD_ENTRY(buffer, data, timestamp) sprintf(buffer, \
		"INSERT INTO ActuatorHealths VALUES ('%.10E', '%.10E', '%.10E', '%.10E', '%s');", \
		data->current_servo_1, \
		data->current_servo_2, \
		data->current_servo_3, \
		data->current_servo_4, \
		timestamp); 
	#define ACTUATORHEALTHS_API_PATH WEB_SERVER_URL "/api/data/ActuatorHealths"
	#define ACTUATORHEALTHS_SQL_SELECT_TO_JSON(sql_row_values) "{ %m: %s, %m: %s, %m: %s, %m: %s, %m: %s }", \
			MG_ESC("current_servo_1"), sql_row_values[0], \
			MG_ESC("current_servo_2"), sql_row_values[1], \
			MG_ESC("current_servo_3"), sql_row_values[2], \
			MG_ESC("current_servo_4"), sql_row_values[3], \
			MG_ESC("timestamp"), sql_row_values[4]
#endif

struct ParachuteDeploymentPhase {
	uint8_t deployed;
	float eta_to_deployment;
	time_t timestamp;
};
#define PARACHUTEDEPLOYMENTPHASE_MSG_ID 6
#define PARACHUTEDEPLOYMENTPHASE_SIZE sizeof(struct ParachuteDeploymentPhase)
#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define PARACHUTEDEPLOYMENTPHASE_SQL_TABLE_GEN "CREATE TABLE ParachuteDeploymentPhase ( " \
		"deployed int," \
		"eta_to_deployment real," \
		"time datetime PRIMARY KEY);"
	#define PARACHUTEDEPLOYMENTPHASE_SQL_GET_MOST_RECENT "SELECT TOP 1 deployed, eta_to_deployment, time FROM ParachuteDeploymentPhase ORDER BY time"
	#define PARACHUTEDEPLOYMENTPHASE_SQL_ADD_ENTRY(buffer, data, timestamp) sprintf(buffer, \
		"INSERT INTO ParachuteDeploymentPhase VALUES ('%d', '%.10E', '%s');", \
		data->deployed, \
		data->eta_to_deployment, \
		timestamp); 
	#define PARACHUTEDEPLOYMENTPHASE_API_PATH WEB_SERVER_URL "/api/data/ParachuteDeploymentPhase"
	#define PARACHUTEDEPLOYMENTPHASE_SQL_SELECT_TO_JSON(sql_row_values) "{ %m: %s, %m: %s, %m: %s }", \
			MG_ESC("deployed"), sql_row_values[0], \
			MG_ESC("eta_to_deployment"), sql_row_values[1], \
			MG_ESC("timestamp"), sql_row_values[2]
#endif

/**
 * Calculates the size of a message given its ID
 * @param id	the ID of the message
 * @return		the size of the message in bytes, or -1 if the message id is invalid
 */
int get_msg_size(int message_id);

/**
 * Returns true if this message id corresponds to a data packet, and false otherwise
 */
bool is_data_send_msg(int message_id);

#ifdef INCLUDE_PROTOCOL_SQL_MACROS
	#define MAX_SQL_WRITE_CMD_SIZE 168

	#define ALL_SQL_TABLE_CREATE_COMMANDS ROCKETKINEMATICS_SQL_TABLE_GEN, MASTERELECTRIC_SQL_TABLE_GEN, ROCKETSTATE_SQL_TABLE_GEN, ACTUATORHEALTHS_SQL_TABLE_GEN, PARACHUTEDEPLOYMENTPHASE_SQL_TABLE_GEN

	#define NUM_SQL_TABLES 5

	#define ALL_API_DATA_PATHS ROCKETKINEMATICS_API_PATH, MASTERELECTRIC_API_PATH, ROCKETSTATE_API_PATH, ACTUATORHEALTHS_API_PATH, PARACHUTEDEPLOYMENTPHASE_API_PATH

   /**
	 * Takes a recieved data packet and converts it into an SQL command
	 * 
	 * @param message_id	The id associated with this message
	 * @param data			The data recieved (as an array of bytes)
	 * @param sql_cmd		A char* buffer where the SQL command will be saved (must be at least as big as MAX_SQL_WRITE_CMD_SIZE)
	 * 
	 * @return				true if the operation was successful, and false otherwise.
	 */
	bool convert_data_msg_to_sql_cmd(int message_id, uint8_t *data, char *sql_cmd);

	#define HANDLE_API_INPUT(db, hm) 		if (mg_match(hm->uri, mg_str(ROCKETKINEMATICS_API_PATH), NULL)) { \
			char** data; \
			query_sql_with_callback(db, &data, ROCKETKINEMATICS_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", ROCKETKINEMATICS_SQL_SELECT_TO_JSON(data)); \
		} else 		if (mg_match(hm->uri, mg_str(MASTERELECTRIC_API_PATH), NULL)) { \
			char** data; \
			query_sql_with_callback(db, &data, MASTERELECTRIC_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", MASTERELECTRIC_SQL_SELECT_TO_JSON(data)); \
		} else 		if (mg_match(hm->uri, mg_str(ROCKETSTATE_API_PATH), NULL)) { \
			char** data; \
			query_sql_with_callback(db, &data, ROCKETSTATE_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", ROCKETSTATE_SQL_SELECT_TO_JSON(data)); \
		} else 		if (mg_match(hm->uri, mg_str(ACTUATORHEALTHS_API_PATH), NULL)) { \
			char** data; \
			query_sql_with_callback(db, &data, ACTUATORHEALTHS_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", ACTUATORHEALTHS_SQL_SELECT_TO_JSON(data)); \
		} else 		if (mg_match(hm->uri, mg_str(PARACHUTEDEPLOYMENTPHASE_API_PATH), NULL)) { \
			char** data; \
			query_sql_with_callback(db, &data, PARACHUTEDEPLOYMENTPHASE_SQL_GET_MOST_RECENT); \
			mg_http_reply(c, 200, "Content-Type: application/json\r\n", PARACHUTEDEPLOYMENTPHASE_SQL_SELECT_TO_JSON(data)); \
		}

#endif

#endif