// WARNING: THIS IS AN AUTOGENERATED FILE. DO NOT EDIT MANUALLY.
// Edit the template in scripts/codegen/templates/port.h.jinja instead

#ifndef PORT_H
#define PORT_H

#include "main.h"

extern UART_HandleTypeDef huart3;
#define debug_uart huart3

#define LED1_GPIO_PORT GPIOB
#define LED1_PIN GPIO_PIN_0
#define LED2_GPIO_PORT GPIOE
#define LED2_PIN GPIO_PIN_1
#define LED3_GPIO_PORT GPIOB
#define LED3_PIN GPIO_PIN_14

#endif