#ifndef PORT_H
#define PORT_H

// This code has been autogenerated, do not modify!

#include "main.h"

extern UART_HandleTypeDef huart3;
#define debug_uart huart3

#define LED1_GPIO_PORT GPIOA
#define LED1_PIN GPIO_PIN_1
#define LED2_GPIO_PORT GPIOA
#define LED2_PIN GPIO_PIN_3
#define LED3_GPIO_PORT GPIOB
#define LED3_PIN GPIO_PIN_10

#endif