name: Check CMake Build

on:
  push:
    branches: ["main", "project/*"]
  pull_request: 
    branches: ["main", "project/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi ninja-build cppcheck
    
    - name: Configure CMake
      run: cmake --preset dev -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"

    - name: Build project
      run: cmake --build --preset dev

    - name: Run cppcheck
      run: cppcheck --project=build/dev/compile_commands.json --enable=all --suppress=missingIncludeSystem --suppress=missingInclude --suppress=unusedFunction --error-exitcode=1 -i targets 
