name: Check CMake Build

on:
  push:
    branches: ["main", "project/*"]
  pull_request: 
    branches: ["main", "project/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi ninja-build cppcheck
        pip install uv

    
    - name: Build and check (ncl-f429-dev)
      run: .github/scripts/build_and_check.sh ncl-f429-dev

    - name: Build and check (ncl-h723-dev)
      run: .github/scripts/build_and_check.sh ncl-h723-dev